<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>HttpHybridCacheHandler.ContentStore.FileSystem.Tests</AssemblyName>
    <RootNamespace>DamianH.HttpHybridCacheHandler.ContentStore.FileSystem.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="10.8.0" />
    <PackageReference Include="xunit.v3.core.mtp-v2" Version="3.2.2" />
    <PackageReference Include="xunit.v3.assert" Version="3.2.2" />
    <ProjectReference Include="..\..\src\HttpHybridCacheHandler.ContentStore.FileSystem\HttpHybridCacheHandler.ContentStore.FileSystem.csproj" />
  </ItemGroup>
</Project>
