<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>DamianH.HttpHybridCacheHandler</RootNamespace>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Shouldly" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.9.0" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="xunit.v3.core.mtp-v2" Version="3.2.2" />
    <ProjectReference Include="..\..\src\HttpHybridCacheHandler.ContentStore.GoogleCloudStorage\HttpHybridCacheHandler.ContentStore.GoogleCloudStorage.csproj" />
  </ItemGroup>
</Project>
