<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DamianH.Http.ForwardedHeaders</RootNamespace>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="xunit.v3.core.mtp-v2" Version="3.2.2" />
    <ProjectReference Include="..\..\src\Http.ForwardedHeaders\Http.ForwardedHeaders.csproj" />
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
