name: hybrid-cache-handler/ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '**'
    paths:
      - .github/BuildHelpers/**
      - .github/workflows/hybrid-cache-handler-ci.yml
      - .github/workflows/ci-template.yml
      - .github/workflows/hybrid-cache-handler-release.yml
      - .github/workflows/release-template.yml
      - hybrid-cache-handler/**
      - .editorconfig
      - Directory.Build.props
      - global.json
      - http-lib.slnx
  pull_request:
    paths:
      - .github/BuildHelpers/**
      - .github/workflows/hybrid-cache-handler-ci.yml
      - .github/workflows/ci-template.yml
      - .github/workflows/hybrid-cache-handler-release.yml
      - .github/workflows/release-template.yml
      - hybrid-cache-handler/**
      - .editorconfig
      - Directory.Build.props
      - global.json
      - http-lib.slnx

jobs:
  build:
    uses: ./.github/workflows/ci-template.yml
    with:
      product: hybrid-cache-handler
      test-targets: '["test-handler", "test-azureblob", "test-s3", "test-gcs", "test-filesystem"]'
      os-matrix: '["ubuntu-latest", "windows-latest"]'
      pack-target: pack-all
