name: signatures/ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '**'
    paths:
      - .github/BuildHelpers/**
      - .github/workflows/signatures-ci.yml
      - .github/workflows/ci-template.yml
      - signatures/**
      - structured-field-values/**
      - .editorconfig
      - Directory.Build.props
      - global.json
      - http-lib.slnx
  pull_request:
    paths:
      - .github/BuildHelpers/**
      - .github/workflows/signatures-ci.yml
      - .github/workflows/ci-template.yml
      - signatures/**
      - structured-field-values/**
      - .editorconfig
      - Directory.Build.props
      - global.json
      - http-lib.slnx

jobs:
  build:
    uses: ./.github/workflows/ci-template.yml
    with:
      product: signatures
      test-targets: '["test"]'
