name: structured-field-values/release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (x.y.z or x.y.z-prerelease.1)'
        required: true
        type: string

jobs:
  release:
    uses: ./.github/workflows/release-template.yml
    with:
      product: structured-field-values
      package: DamianH.Http.StructuredFieldValues
      tag-prefix: sfv-v
      version: ${{ inputs.version }}
    secrets:
      NUGET_ORG_APIKEY: ${{ secrets.NUGET_ORG_APIKEY }}
